/** Declaration file generated by dts-gen */

declare module 'concretejs' {
  export class Hit {
    constructor(config?: any);

    context: any;

    canvas: any;

    clear(): any;

    getColorFromIndex(index: any): any;

    getIntersection(x: any, y: any): any;

    intToRGB(number: any): any;

    rgbToInt(rgb: any): any;

    setSize(width: any, height: any): any;
  }

  export class Layer {
    constructor(config?: any);

    scene: Scene;

    hit: Hit;

    visible: boolean;

    destroy(): void;

    getIndex(): any;

    moveDown(): any;

    moveToBottom(): any;

    moveToTop(): void;

    moveUp(): any;

    setPosition(x: any, y: any): any;

    setSize(width: any, height: any): any;
  }

  export class Scene {
    constructor(config?: any);

    context: any;

    canvas: any;

    clear(): any;

    download(config: any): void;

    setSize(width: any, height: any): any;

    toImage(callback: any): void;
  }

  export class Viewport {
    constructor(config?: any);

    scene: Scene;

    add(layer: any): any;

    destroy(): void;

    getIndex(): any;

    getIntersection(x: any, y: any): any;

    render(): void;

    setSize(width: any, height: any): any;
  }

  export const PIXEL_RATIO: number;

  export const viewports: Viewport[];
}
